databases:
  - name: viewing_party_api
    databaseName: viewing_party_api
    user: jonathanatkins  
    plan: free

services:
  - type: web
    name: viewing-party-api
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: viewing_party_api  
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2